app_ids:
  cbe: 'com.combanketh.mobilebanking' 
  boa: 'com.boa.boaMobileBanking'
  dashen: 'com.dashen.dashensuperapp'
bank_names:
  cbe: 'Commercial Bank of Ethiopia'
  boa: 'Bank of Abyssinia'
  dashen: 'Dashen Bank'
database:
  user: 'postgres'
  password: 'Yon24'
  dbname: 'bank_reviews'
  host: 'localhost'
  port: '5432'